# Use the official Node.js 20 image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the working directory
COPY ./package.json ./pnpm-lock.yaml ./

# Install pnpm
RUN npm install -g pnpm

# Install all dependencies
RUN pnpm install

# Copy the rest of the application
COPY . .

# Build the TypeScript code
RUN pnpm run build

# Expose the port the app runs on
EXPOSE 5173

# Run the frontend
CMD ["pnpm", "dev"]