services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - .:/backend/app

  ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile.ui
    ports:
      - "5173:5173"
    volumes:
      - .:/frontend/app
