services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - .:/backend/app

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "5173:5173"
    volumes:
      - .:/frontend/app
