# Use a python base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the backend poetry.lock and pyproject.toml files
COPY ./backend/poetry.lock ./backend/pyproject.toml ./

# Install poetry
RUN pip install poetry

# Install dependencies
RUN poetry install

# Copy the backend source code
COPY ./backend .

# Expose the port
EXPOSE 8000

# Run the backend
CMD ["poetry", "run", "uvicorn", "multimodalexplorer.main:app", "--port", "8000"]