# Copyright (c) Meta Platforms, Inc. and affiliates.

# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Use CUDA base image
FROM nvidia/cuda:11.1.1-cudnn8-runtime-ubuntu20.04

# Set the working directory
WORKDIR /app

# TODO: Finish implementation for the FAISS Index service